using System.Runtime.Serialization;

namespace JudoPayDotNet.Models
{
    [DataContract]
    public class GooglePayWalletModel
    {
        /// <summary>
        /// JSON serialized payment token generated by Google Pay API
        /// </summary>
        [DataMember(IsRequired = true)]
        public string Token { get; set; }

        /// <summary>
        /// The payment card network returned by Google Pay API. Value should match one of the allowedCardNetworks
        /// in https://developers.google.com/pay/api/web/reference/request-objects#CardParameters
        /// </summary>
        [DataMember(IsRequired = true)]
        public string CardNetwork { get; set; }

        /// <summary>
        /// The details about the card returned by Google Pay API. This value is commonly the last four digits of
        /// the selected payment account number.
        /// </summary>
        [DataMember(IsRequired = true)]
        public string CardDetails { get; set; }
    }
}