version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  dotnet_restore:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-dotnet-sdk-{{ checksum "JudoPayDotNet/JudoPayDotNet.csproj" }}-{{ checksum "JudoPayDotNetTests/JudoPayDotNetTests.csproj" }}-{{checksum "JudoPayDotNetIntegrationTests/JudoPayDotNetIntegrationTests.csproj" }}
      - run:
          name: Dotnet Restore
          command: dotnet restore
      - save_cache:
          key: judokit-dotnet-sdk-{{ checksum "JudoPayDotNet/JudoPayDotNet.csproj" }}-{{ checksum "JudoPayDotNetTests/JudoPayDotNetTests.csproj" }}-{{checksum "JudoPayDotNetIntegrationTests/JudoPayDotNetIntegrationTests.csproj" }}
          paths: ~/.nuget/packages
  build_sdk:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-dotnet-sdk-{{ checksum "JudoPayDotNet/JudoPayDotNet.csproj" }}-{{ checksum "JudoPayDotNetTests/JudoPayDotNetTests.csproj" }}-{{checksum "JudoPayDotNetIntegrationTests/JudoPayDotNetIntegrationTests.csproj" }}
      - run:
          name: Install Sonar Scanner
          shell: cmd.exe
          command: choco install sonarscanner-msbuild-net46 -y
      - run:
          name: Build SDK
          shell: powershell.exe
          command: |
            if (!($env:APPVEYOR_PULL_REQUEST_NUMBER)) {
              &SonarScanner.MSBuild.exe begin \
                /k:"DotNetSDK" \
                /o:"judopay" \
                /d:"sonar.host.url=https://sonarcloud.io" \
                /d:"sonar.login=$env:SONARCLOUD_TOKEN" \
            } Else {
              &SonarScanner.MSBuild.exe begin \
                /k:"DotNetSDK" \
                /o:"judopay" \
                /d:"sonar.host.url=https://sonarcloud.io" \
                /d:"sonar.login=$env:SONARCLOUD_TOKEN" \
                /d:"sonar.pullrequest.base=$env:APPVEYOR_REPO_BRANCH" \
                /d:"sonar.pullrequest.key=$env:APPVEYOR_PULL_REQUEST_NUMBER" \
                /d:"sonar.pullrequest.branch=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH" \
                /d:"sonar.pullrequest.provider=GitHub" \
                /d:"sonar.github.repository=$env:APPVEYOR_REPO_NAME" \
            }
            &dotnet build JudoPayDotNet
            &SonarScanner.MSBuild.exe end \
              /d:"sonar.login=$env:SONARCLOUD_TOKEN"
  unit_test_sdk:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-dotnet-sdk-{{ checksum "JudoPayDotNet/JudoPayDotNet.csproj" }}-{{ checksum "JudoPayDotNetTests/JudoPayDotNetTests.csproj" }}-{{checksum "JudoPayDotNetIntegrationTests/JudoPayDotNetIntegrationTests.csproj" }}
      - run:
          name: Dotnet Test
          command: dotnet test JudoPayDotNetTests --no-build
  integration_test_sdk:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-dotnet-sdk-{{ checksum "JudoPayDotNet/JudoPayDotNet.csproj" }}-{{ checksum "JudoPayDotNetTests/JudoPayDotNetTests.csproj" }}-{{checksum "JudoPayDotNetIntegrationTests/JudoPayDotNetIntegrationTests.csproj" }}
      - run:
          name: Dotnet Test
          command: dotnet test JudoPayDotNetIntegrationTests --no-build
  release_sdk:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Transform csproj File
          command: echo "test"
      - run:
          name: Dotnet Nuget Push
          command: dotnet nuget push --api-key %NUGET_API_KEY%
  report_to_jira:
    docker:
      - image: gcr.io/opnf-management/deployer:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: Report Deployment to Jira
          environment:
            ENVIRONMENT: << parameters.environment >>
          command: /resources/scripts/report-status-to-jira.sh

workflows:
  version: 2
  build:
    jobs:
      - dotnet_restore:
          filters:
            tags:
              only:
                - /^v[0-9]+(\.[0-9]+)*$/
      - build_sdk:
          context: shared-secrets
          requires:
            - dotnet_restore
          filters:
            tags:
              only:
                - /^v[0-9]+(\.[0-9]+)*$/
      - unit_test_sdk:
          requires:
            - build_sdk
      - integration_test_sdk:
          requires:
            - build_sdk
      - release_sdk:
          context: shared-secrets
          requires:
            - build_sdk
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v[0-9]+(\.[0-9]+)*$/
      - report_to_jira:
          context: shared-secrets
          environment: prod
          requires:
            - release_sdk
          filters:
            tags:
              only:
                - /^v[0-9]+(\.[0-9]+)*$/
