name: .NET Publish SDK

on:
  pull_request:
  workflow_dispatch:
jobs:
  build_and_test:
    uses: Judopay/github-actions/.github/workflows/dotnet-publish.yml@master
    with:
      version: 
    secrets:
      nuget_api_key: ${{ secrets.nuget_api_key }}
